/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type CloudProvider = 'aws' | 'gcp' | 'minio';

export type ConfidenceLevel = 'CONFIRMED' | 'HIGH' | 'LOW' | 'MEDIUM';

export type DecisionType = 'ALLOW' | 'BLOCK' | 'ERROR' | 'QUARANTINE';

export type FileStatus =
  | 'BLOCKED'
  | 'DELETED'
  | 'ERROR'
  | 'IN_REVIEW'
  | 'PROMOTED'
  | 'PROMOTING'
  | 'QUARANTINED'
  | 'SCANNED'
  | 'SCANNING';

export type FindingOutcome = 'ERROR' | 'FAIL' | 'PASS' | 'SKIPPED' | 'SUSPICIOUS';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type JobStatus = 'DEAD' | 'FAILED' | 'QUEUED' | 'RUNNING' | 'SUCCEEDED';

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type SessionStatus = 'CREATED' | 'EXPIRED' | 'FAILED' | 'UPLOADED' | 'UPLOADING';

export type SeverityLevel = 'CRITICAL' | 'HIGH' | 'INFO' | 'LOW' | 'MEDIUM';

export type StorageZone = 'audit' | 'clean' | 'quarantine' | 'replica';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = 'admin' | 'analyst' | 'auditor';

export interface ApiKeys {
  application_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  expires_at: Timestamp | null;
  id: Generated<string>;
  key_hmac: Buffer;
  key_prefix: string;
  last_used_at: Timestamp | null;
  revoked_at: Timestamp | null;
  scopes: Generated<string[]>;
}

export interface Applications {
  active_policy_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  owner_user_id: string;
  webhook_secret: Buffer | null;
  webhook_url: string | null;
}

export interface AuditCheckpoints {
  chain_hash: Buffer;
  created_at: Generated<Timestamp>;
  gcs_generation: string | null;
  id: Generated<string>;
  last_seq: Int8;
  s3_version_id: string | null;
  signature: Buffer;
}

export interface AuditEvents {
  action: string;
  actor_id: string;
  actor_type: string;
  application_id: string | null;
  decision_id: string | null;
  details: Generated<Json>;
  event_hash: Buffer;
  file_id: string | null;
  file_version_id: string | null;
  id: Generated<string>;
  ip: string | null;
  occurred_at: Generated<Timestamp>;
  prev_hash: Buffer;
  request_id: string | null;
  seq: Generated<Int8>;
}

export interface CloudObjects {
  bucket: string;
  crc32c: string | null;
  created_at: Generated<Timestamp>;
  enc_alg: string | null;
  etag: string | null;
  file_version_id: string;
  id: Generated<string>;
  kek_id: string | null;
  object_key: string;
  provider: CloudProvider;
  sha256_cipher: Buffer | null;
  sha256_plain: Buffer | null;
  size_bytes: Int8;
  storage_version_id: string;
  zone: StorageZone;
}

export interface Files {
  application_id: string;
  created_at: Generated<Timestamp>;
  current_version_id: string | null;
  deleted_at: Timestamp | null;
  display_filename: string;
  id: Generated<string>;
  status: Generated<FileStatus>;
  upload_session_id: string;
}

export interface FileVersions {
  bucket: string;
  created_at: Generated<Timestamp>;
  etag: string | null;
  file_id: string;
  id: Generated<string>;
  object_key: string;
  provider: CloudProvider;
  sha256_ingest: Buffer;
  size_bytes: Int8;
  storage_version_id: string;
  version_no: Generated<number>;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PromotionJobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  decision_id: string;
  finished_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  outcome: string | null;
  run_after: Generated<Timestamp>;
  status: Generated<JobStatus>;
}

export interface RefreshTokens {
  expires_at: Timestamp;
  id: Generated<string>;
  replaced_by: string | null;
  revoked_at: Timestamp | null;
  token_hash: Buffer;
  user_id: string;
}

export interface ReplicationJobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  run_after: Generated<Timestamp>;
  source_cloud_object_id: string;
  status: Generated<JobStatus>;
  target_bucket: string;
  target_provider: CloudProvider;
  verified_at: Timestamp | null;
}

export interface ScanJobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  file_version_id: string;
  finished_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  run_after: Generated<Timestamp>;
  status: Generated<JobStatus>;
}

export interface ScanResults {
  check_id: string;
  confidence: Generated<ConfidenceLevel>;
  created_at: Generated<Timestamp>;
  duration_ms: number | null;
  engine: string;
  engine_version: string | null;
  evidence: Generated<Json>;
  file_version_id: string;
  id: Generated<string>;
  outcome: FindingOutcome;
  reason_code: string | null;
  scan_job_id: string;
  scanned_sha256: Buffer;
  scanned_size: Int8;
  scanned_storage_version_id: string;
  severity: Generated<SeverityLevel>;
  signature_version: string | null;
}

export interface SecurityDecisions {
  authorization_result: string;
  bound_bucket: string;
  bound_key: string;
  bound_sha256: Buffer;
  bound_size: Int8;
  bound_storage_version_id: string;
  confidence: ConfidenceLevel;
  created_at: Generated<Timestamp>;
  decided_by: string;
  decision: DecisionType;
  engine_version: string;
  file_version_id: string;
  id: Generated<string>;
  integrity_result: string;
  policy_id: string;
  policy_result: string;
  primary_reason: string;
  record: Json;
  risk_score: number;
  scan_job_id: string | null;
  scanner_result: string;
  severity: SeverityLevel;
  supersedes_id: string | null;
}

export interface SecurityPolicies {
  application_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  document: Json;
  document_sha256: Buffer;
  id: Generated<string>;
  version: number;
}

export interface UploadSessions {
  api_key_id: string;
  application_id: string;
  client_ip: string | null;
  client_ref: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  declared_mime: string;
  declared_sha256: Buffer | null;
  declared_size: Int8;
  expires_at: Timestamp;
  id: Generated<string>;
  original_filename: string;
  policy_id: string;
  status: Generated<SessionStatus>;
  token_jti: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  failed_logins: Generated<number>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  password_hash: string;
  role: UserRole;
}

export interface DB {
  api_keys: ApiKeys;
  applications: Applications;
  audit_checkpoints: AuditCheckpoints;
  audit_events: AuditEvents;
  cloud_objects: CloudObjects;
  file_versions: FileVersions;
  files: Files;
  pgmigrations: Pgmigrations;
  promotion_jobs: PromotionJobs;
  refresh_tokens: RefreshTokens;
  replication_jobs: ReplicationJobs;
  scan_jobs: ScanJobs;
  scan_results: ScanResults;
  security_decisions: SecurityDecisions;
  security_policies: SecurityPolicies;
  upload_sessions: UploadSessions;
  users: Users;
}
